name: Daily Rebuild and Deploy

on:
  schedule:
    - cron: '0 2 * * *' # Runs at 2:00 AM UTC every day

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the Astro Site
      - name: Build Site
        run: npm run build

      # Step 5: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
